SET NAMES utf8;

CREATE DATABASE gbs;
USE gbs;

CREATE TABLE GUESTBOOK
(
  ID           INT  NOT NULL   PRIMARY KEY AUTO_INCREMENT,
  NAME         VARCHAR(20) NOT NULL,
  PHONE        VARCHAR(20),
  EMAIL        VARCHAR(40),
  TITLE        VARCHAR(80) NOT NULL,
  CONTENT      VARCHAR(2000),
  CREATED_TIME TIMESTAMP NOT NULL DEFAULT NOW()
);
